# Generated by Django 4.1.2 on 2023-02-21 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Rating')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(upload_to='restaurant_images/', verbose_name='Image')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13, verbose_name='Longitude')),
                ('opens_at', models.TimeField(verbose_name='Opens At')),
                ('closes_at', models.TimeField(verbose_name='Closes At')),
                ('opened', models.BooleanField(default=False, verbose_name='Opened')),
                ('geofence_id', models.CharField(max_length=300, verbose_name='Geofence')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantCuisines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(max_length=250, null=True, verbose_name='Cuisine')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='cuisine_images/', verbose_name='Image')),
                ('cuisine_type', models.PositiveSmallIntegerField(choices=[(1, 'Veg'), (2, 'Non Veg')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('stocks', models.PositiveIntegerField(default=0, verbose_name='Stocks')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='restaurant.restaurant')),
            ],
        ),
    ]
