# Generated by Django 4.1.2 on 2023-02-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='specials',
            field=models.TextField(null=True, verbose_name='Restaurant Sepecials'),
        ),
    ]
