# Generated by Django 4.1.2 on 2023-02-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='CartItemModel',
        ),
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
