# Generated by Django 4.1.2 on 2023-02-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_specials'),
        ('cart', '0006_alter_cartitemmodel_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='cuisine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisin', to='restaurant.restaurantcuisines'),
        ),
    ]
