# Generated by Django 4.1.2 on 2023-02-27 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_specials'),
        ('cart', '0007_alter_cartitemmodel_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurant.restaurant'),
        ),
    ]
