# Generated by Django 4.1.2 on 2023-03-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending for restaurant to confirm'), (2, 'Restaurant Confirmed'), (3, 'Cooking Your Cusine'), (4, 'Out For Delivery'), (5, 'Delivered'), (6, 'Yor Order is cancelled')], default=1),
        ),
    ]
